### ISSUE TITLE
❔ Help commands 

### ISSUE THREAD

**Issue by izzylys** [izzylys/LeafBot#9]
we need some basic help and info commands so people can learn how to use our fresh and leafy bot 🍃

**Comment by Killeroo** [comment]
If you have a layout for !help or something then we can structure it in this ticket and then I'll add it. If you want we can split it out so we have something like !commands to see all the commands. I actually quite like how Dyno.gg sent the command list straight to you but yeah what you think?

**Comment by Killeroo** [comment]
Auto role assign to 'other losers' / welcome message
!help dms info, basic commands and bunny pic
!about info about bot
!commands lists all commands
Custom help formatter for commands
Commands executed and number of guilds on status

**Comment by Killeroo** [comment]
Added as of https://github.com/izzylys/LeafBot/commit/9080375a2ef1d12dbe4b99613fbd6478c2132a0a

**Comment by izzylys** [comment]
closed by #18

**Comment by izzylys** [comment]
lol beat me to it by like .2 seconds
